# Generated by Django 3.1 on 2020-12-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0024_userskills_expertise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userskills',
            name='expertise',
            field=models.IntegerField(choices=[(0, 'Low'), (1, 'Normal'), (2, 'High')], default=0),
        ),
    ]
